dependency "vpc" {
  config_path = "../vpc"
}


# Include the top-level terragrunt.hcl file
# That will:
# - Manage the remote_state
# - Manage the default Provider(s)
# - Assign some inputs (e.g. account, region, environment)
include "root" {
  path = find_in_parent_folders()
}


# Set some parameters (inputs) for this module
#include "main_module" {
#  path = "${dirname(find_in_parent_folders())}/_env_common/aws/sagemaker.hcl"
#}


# Include our module by dynamically create some terraform code here.
terraform {
  # Keep this as a reminder to move to git-based modules
  #source = "${local.base_source_url}?ref=v0.7.0"
  #
  # Local module (for rapid dev)
  source = "${dirname(find_in_parent_folders())}//_modules/aws/sagemaker"
}


# MODULE PARAMETERS
#   These are the variables we have to pass in to use the module.
#   This defines the parameters that are common across all environments.
#   TG transforms these to "TF_VAR_<input_name>=<input_value>" in the TF run.
#
# Extra/unused inputs are ignored since they're just passed as environment variables
inputs = {
  owner = "admin"

  auth_mode = "IAM"

  domain_name = "sagemaker-domain-1"

  # VPC
  vpc_id = dependency.vpc.outputs.vpc_id
  
  # Use all the private subnets
  subnet_ids = dependency.vpc.outputs.private_subnets



  # SAGEMAKER ARGS
  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#argument-reference


  # TODO

  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#retention_policy
  # retention_policy = "Delete"

  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#repository_url
  # repository_url

  # https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-available-instance-types.html
  # default_resource_spec

  # Set instance type
  # https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-available-instance-types.html

  # Don't use role generated by the module in this code (but this is ok for now)
  # execution_role

}
