# https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/kubernetes.html

# Kubernetes secret for the container registry to pull private containers.
pull_secret: ngc-registry

# Amount of system memory to allocate in Pods. Should end in "Gi" for gigabytes.
shm_size: 512Gi

# Hostname or IP address for the NFS server where data is stored.
nfs_server: 192.168.3.196

# Path to store data in the NFS server.
nfs_path: /mnt/myshareddir

# Specify the resource name for IB devices according to kubernetes, such as "nvidia.com/hostdev" for Mellanox IB adapters.
#ib_resource_name: "nvidia.com/hostdev"

# Specify the number of IB devices to include per node in each pod.
#ib_count: "8"

# Specify a dnsPolicy to use in all pods, if necessary
dns_policy: null


# bcm.yaml
#
#partition: null
#account: null
#exclusive: True
#gpus_per_task: null
#gpus_per_node: 8
#mem: 0
#job_name_prefix: 'nemo-megatron-'
#srun_args:
#  - "--no-container-mount-home"
